name: lick-fun-indexer

handlers: src

contracts:
  - name: Factory
    abi_file_path: "./abis/Factory.json"
    events:
      - event: "TokenCreated(address indexed token, address indexed curve, address indexed creator)"

  - name: BondingCurve
    abi_file_path: "./abis/BondingCurve.json"
    events:
      - event: "CurveLaunch(address indexed token, uint256 startTime, uint256 startBlock)"
      - event: "CurveBuy(address indexed buyer, address indexed token, uint256 amountIn, uint256 amountOut)"
      - event: "CurveSell(address indexed seller, address indexed token, uint256 amountIn, uint256 amountOut)"
      - event: "CurveGraduate(address indexed token, address indexed pool)"

chains:
  - id: 10143
    hypersync_config:
      url: https://monad-testnet.hypersync.xyz
    start_block: 39486047
    contracts:
      - name: Factory
        address: "0xe5a63a3496952bb12e4802264244d476a8f36eed"
      - name: BondingCurve
